
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mander.myapplication.analyzers.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 31;
  public static final int CADENA = 2;
  public static final int DIVISION = 8;
  public static final int SUMA = 5;
  public static final int LLAVEI = 13;
  public static final int ETIQUETAS = 21;
  public static final int EJECUTAR = 27;
  public static final int LLAVED = 14;
  public static final int YAXIS = 20;
  public static final int COMILLAS = 4;
  public static final int MULTIPLI = 7;
  public static final int TIPO = 24;
  public static final int VALORES = 22;
  public static final int BARRAS = 16;
  public static final int COMA = 30;
  public static final int CORCHI = 11;
  public static final int TOTAL = 25;
  public static final int EOF = 0;
  public static final int DEF = 15;
  public static final int PIE = 17;
  public static final int CORCHD = 12;
  public static final int EXTRA = 26;
  public static final int PARENTI = 9;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int XAXIS = 19;
  public static final int PUNTOCOMA = 29;
  public static final int PARENTD = 10;
  public static final int COMENTARIO = 28;
  public static final int UNIR = 23;
  public static final int TITULO = 18;
  public static final int RESTA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "NUMERO",
  "COMILLAS",
  "SUMA",
  "RESTA",
  "MULTIPLI",
  "DIVISION",
  "PARENTI",
  "PARENTD",
  "CORCHI",
  "CORCHD",
  "LLAVEI",
  "LLAVED",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "XAXIS",
  "YAXIS",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "COMENTARIO",
  "PUNTOCOMA",
  "COMA",
  "DOSPUNTOS"
  };
}

